# 项目相关配置
halcyon:
  # 名称
  name: Halcyon
  version: 1.0.0
spring:
  application:
    name: halcyon
  profiles:
    active: dev
    # Servlet 配置
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小
  # 邮箱模版引擎
  freemarker:
    template-loader-path: classpath:/templates/
    default-encoding: UTF-8
  # 邮箱
  mail:
    host: smtp.163.com
    username: twinkleblog@163.com
    password: XBSTSMIJLHMYAIOT
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
--- #------------------------mybatis-plus配置--------------------------------
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键自增
      id-type: auto
      # 全局逻辑删除字段名
      logic-delete-field: del_flag
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/**/*.xml
--- #------------------------Sa-Token 配置--------------------------------
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 3600
  # jwt秘钥
  jwt-secret-key: ogndsfgjwgmlkemtrekwngviewjvremtrewfwe
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 是否从cookie中读取token
  is-read-cookie: false